# Generated by Django 5.0.3 on 2024-04-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger_Flight',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=35)),
                ('cnic', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger_Flight_Combined',
            fields=[
                ('passenger_flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_flight', models.DateField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.passenger_flight')),
            ],
        ),
    ]
