# Generated by Django 5.0.3 on 2024-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline_Login_Users',
            fields=[
                ('airline_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('airline_user_email', models.EmailField(max_length=254, unique=True)),
                ('airline_user_name', models.CharField(max_length=30)),
                ('airline_user_password', models.CharField(max_length=30)),
                ('airline_user_type', models.CharField(max_length=30)),
            ],
        ),
    ]
