# Generated by Django 5.0.3 on 2024-07-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_airline_login_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline_login_users',
            name='profile_picture',
            field=models.ImageField(default=True, upload_to='profile_pics'),
        ),
    ]
